### ISSUE TITLE
[Feature request][DateRange]label customization

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/SonataCoreBundle#110]
I'm using the 'sonata_type_date_range' on a french website, and for the moment, I'm stuck with 'start' and 'end'. I used [this solution](https://groups.google.com/forum/#!msg/sonata-users/QpTjNrJYhKo/ZN-nQC1AadgJ) as a workaround, but I think it is a hack since it uses the `attr` option, which has the side-effect to create an unnecessary html attribute.

**Comment by Renrhaf** [comment]
+1

**Comment by pulzarraider** [comment]
Fixed with #137. Thank you for reporting the issue.

**Comment by Renrhaf** [comment]
Thanks for the fix
