### ISSUE TITLE
Files missing when assets:install on version 2.3.0

### ISSUE THREAD

**Issue by samuel4x4** [sonata-project/SonataCoreBundle#111]
Hi there,

I just updated Sonata Core Bundle to the last version 2.3.0. There seems to be some issues when running assets:install, these required files are missing from the /web directory:

web/bundles/sonatacore/vendor/select2/select2-bootstrap.css"
web/bundles/sonatacore/vendor/ionicons/css/ionicons.min.css"
web/bundles/sonatacore/vendor/bootstrap/dist/css/bootstrap.min.css"
web/bundles/sonatacore/vendor/select2/select2.css"
web/bundles/sonatacore/vendor/jquery/dist/jquery.min.js"
web/bundles/sonatacore/vendor/bootstrap/dist/js/bootstrap.min.js"
web/bundles/sonatacore/vendor/select2/select2.min.js"

I'll try to downgrade now to an older version until the bug will be fixed.

Thanks for your good work ;)

**Comment by Tocacar** [comment]
@pulzarraider I finally managed to get this working.  Thank you for all your help!

**Comment by pulzarraider** [comment]
@Tocacar I'm glad I could help.
