### ISSUE TITLE
Issue deploying on heroku

### ISSUE THREAD

**Issue by marvoh** [sonata-project/SonataCoreBundle#114]
Hi,

How do i deploy assets in heroku? The app cannot find stylesheets but looks fine on my localhost

**Comment by pulzarraider** [comment]
Symfony assets are installed by default in the web directory with the `php app/console assets:install` command. Sonata's assets works same as in other Symfony application.

Heroku is cloud platform. I don't know how it works. Please contact their support if you need help.

Some documentation I have found: https://devcenter.heroku.com/articles/getting-started-with-symfony2#deploying-to-heroku
