### ISSUE TITLE
Add datepicker calender week option

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataCoreBundle#115]
The upcoming version of the https://github.com/Eonasdan/bootstrap-datetimepicker
will feature the `calendar week option`:
https://github.com/Eonasdan/bootstrap-datetimepicker/issues/130
https://github.com/Eonasdan/bootstrap-datetimepicker/pull/478

This could then be added to the `dp_` options:
https://github.com/sonata-project/SonataCoreBundle/blob/master/Form/Type/BasePickerType.php#l80-104

Based on:
http://eonasdan.github.io/bootstrap-datetimepicker/

I guess the default should be set to false.

I will return to this issue as soon the the option has been released.

Who contributes to the datepicker in this CoreBundle?

**Comment by afurculita** [comment]
@webdevilopers the new version of bootstrap datetimepicker has been released https://github.com/Eonasdan/bootstrap-datetimepicker/releases

**Comment by webdevilopers** [comment]
Cool @afurculita . Opened a new issue waiting for some feedback:
https://github.com/sonata-project/SonataCoreBundle/issues/138

**Comment by Bladrak** [comment]
I'm closing this issue, continuing the discussion in #138 :)
