### ISSUE TITLE
bootstrap.css typo ?

### ISSUE THREAD

**Issue by stphnpt** [sonata-project/SonataCoreBundle#126]
Resources/public/vendor/bootstrap/dist/css/bootstrap.css:

.carousel-inner > .item > a > img {
...
  width: 100% \9;
...
}

.img-thumbnail {
...
  width: 100% \9;
...
}

**Comment by pulzarraider** [comment]
A bug in boostrap should be reported to bootstrap's authors.

Anyway `width: 100% \9;` seems to be some kind of CSS hack.
