### ISSUE TITLE
Extract forms to a new bundle

### ISSUE THREAD

**Issue by afurculita** [sonata-project/SonataCoreBundle#135]
SonataCoreBundle contains great form types that are very usable also outside the Sonata project. It will be great to have them as a bundle, to not have to install the whole SonataCoreBundle just to use some of the forms. 
This new bundle can contain form types, data transformers, form extensions, filter form types etc., that can be extracted  from SonataCoreBundle and other sonata bundles.
@rande what do you think?

**Comment by rande** [comment]
There are more 15 bundles in the Sonata Project. This bundle is about extracting core feature from those bundles. So there will not be a new bundle for only form ... the split will be crazy too maintain.

If you don't want a feature, then create a PR to enable only a set of feature (this can be a list of configuration file to load).

**Comment by afurculita** [comment]
@rande Then I would suggest you to bring everything in one repository and use a subtree split to create read-only repositories for all the bundles so you only have one repo to maintain like symfony does. This will allow us to be able to extract more functionality into their own component/bundle.

What do you think?

This way it will be easier for all of us to see the big picture behind the Sonata project and how powerful it is.

**Comment by rande** [comment]
No, This bundle contains and will contains elements shared across Sonata's bundles. This bundle has been created to extract some important features from the AdminBundle. I don't want to split this one again as I don't see the benefit of it.

**Comment by afurculita** [comment]
@rande I was referring to all the bundles from the Sonata project, not particularly to this one. You said that having a big number of bundles it is a nightmare to maintain. I was suggesting as a solution how the Symfony project and many many others are working and how they solved this problem. They gathered everything in one repository and used a subtree split to create read-only repositories for all the bundles. 

A very good example is Sylius (https://github.com/Sylius). They have like 50 bundles/components that they maintain from one repository. Also I like a lot their philosophy to move general code (interfaces, models, builders, independent services etc.) to components. 

Having one repository for all (or almost all of) the sonata subprojects, it will be easier for you to maintain.

**Comment by rande** [comment]
@afurculita ok, yes it is an idea I have in mind for a few months now, something we can do for Symfony3.
