### ISSUE TITLE
Update eonasdan-bootstrap-datetimepicker to current version 4.0

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataCoreBundle#138]
As mentioned by @afurculita in issue https://github.com/sonata-project/SonataCoreBundle/issues/115#issuecomment-72275920 version *4.0* of the `eonasdan-bootstrap-datetimepicker` has been released:
- https://github.com/Eonasdan/bootstrap-datetimepicker/issues/161

This version includes new features like the `calendarWeek` options:
- https://github.com/sonata-project/SonataCoreBundle/issues/115

But they also mention some BC:
- https://github.com/Eonasdan/bootstrap-datetimepicker/releases/tag/v4.0.0
- http://eonasdan.github.io/bootstrap-datetimepicker/Version%204%20Changelog/

Can someone tell if these BC are relevant to the `SonataCoreBundle` ?

If not I could create the PR for the `bower.json` file:
https://github.com/sonata-project/SonataCoreBundle/blob/master/bower.json#L8

Changing dependencies from `"eonasdan-bootstrap-datetimepicker": "3.1.3"` to `"eonasdan-bootstrap-datetimepicker": "4.0.0"`.

Not sure if the version by @Bladrak is a better solution linking the `latest` version:
- https://github.com/sonata-project/SonataCoreBundle/blob/2.2/bower.json

Then I would create a PR on the docs for the new options.

**Comment by webdevilopers** [comment]
Just a short note to myself for the available options:
- http://eonasdan.github.io/bootstrap-datetimepicker/Options/
- http://sonata-project.org/bundles/core/master/doc/reference/form_types.html#sonata-type-date-picker-and-sonata-type-datetime-picker
- https://github.com/sonata-project/SonataCoreBundle/blob/master/Form/Type/BasePickerType.php#l80-104

**Comment by Bladrak** [comment]
Not sure about the BC breaks, I guess we'll have to try it out. Feel free to submit a PR with the updated version if you'd like :)

**Comment by nlzet** [comment]
Did you continue with this? I tried setting up v4 of the datetimepicker, but this won't work out of the box.

And there will be BC breaks, for example in the current way there is a option <code>dp_pick_time</code> to enable/disable the time. In v4 this is defined by checking if there are time units in your date format. ()

Other options have other names or work slightly differently and have different default values like null/false.

How would you like to continue with this ? Should a PR with BC breaks be created ?

**Comment by webdevilopers** [comment]
At least we need a full list of options that have changed.

**Comment by webdevilopers** [comment]
Closing this issue in favor of PR https://github.com/sonata-project/SonataCoreBundle/pull/149 by @nlzet.
