### ISSUE TITLE
Data-date-format doesn't work anymore

### ISSUE THREAD

**Issue by wimpheling** [sonata-project/SonataCoreBundle#145]
My admin line : 

``` php
->add('date', 'sonata_type_date_picker', array('attr' => array('data-date-format' => 'YYYY-MM-DD')))
```

doesn't work any-more. The data-date-format attr of the generated html is not correctly set (I have  data-date-format="D MMM y"  instead).

I made it work again by rolling back to 9a488952c92c890e72def71c2a00651f9e545e34

Is there a new way to configure this parameter ? If so, the doc should be updated or the bug fixed

**Comment by pulzarraider** [comment]
Should be fixed by 615b156e2bae1d8e9e34fedcc22ee6ba897f7872. Thank you for reporting the issue.

**Comment by wimpheling** [comment]
i had seen the date_format arg in the source, but when I tried it I had an error saying the parameter was unknown. I'll try to switch to the commit you indicated and report if it works this week-end.

Thanks for your quick answer!

**Comment by core23** [comment]
Solved? Please close @wimpheling

**Comment by enekochan** [comment]
Using `'date_format' => 'yyyy-MM-dd'` worked for me to change the default `data-date-format` attribute.

**Comment by jordisala1991** [comment]
Old issue with a provided solution, closing.
