### ISSUE TITLE
ResizeFormListener

### ISSUE THREAD

**Issue by druzsek** [sonata-project/SonataCoreBundle#166]
In ResizeFormListener onBind call preSubmit, onBind must call onSubmit.

**Comment by Soullivaneuh** [comment]
@druzsek No. Look at the file, it's to prevent BC compatibility.

At least, we can keep this issue for next **major** release.

**Comment by nandorstanko** [comment]
@Soullivaneuh In this commit https://github.com/sonata-project/SonataCoreBundle/commit/69dbaaa50bec0a3cb1048f1812c13a06faa5380f the onBind is changed to onSubmit and there is a compatibility function onBind, but this function doesn't call the new onSubmit function, instead it calls preSubmit. Is this okay?

**Comment by Soullivaneuh** [comment]
@nandorstanko Not totally true. The `onBind` was changed to `onSubmit` before that commit but the `onBind` method was never called and was BC breaks. This commit fix that.

See here: https://github.com/sonata-project/SonataCoreBundle/commit/69dbaaa50bec0a3cb1048f1812c13a06faa5380f#diff-9da23b066b65d136664680907ab29e94R34

**Comment by nandorstanko** [comment]
@Soullivaneuh I still don't understand why is the preSubmit function called twice, from preBind and from onBind as well. onSubmit is never called this way.

**Comment by Soullivaneuh** [comment]
> onSubmit is never called this way.

`onSubmit` is called on the deprecated method `onBind`: https://github.com/sonata-project/SonataCoreBundle/blob/master/Form/EventListener/FixCheckboxDataListener.php#L48

This is just a wrapper to keep BC if those classes are extended by users. In final, only `onSubmit` do the job.

Or I misunderstand your question.

**Comment by nandorstanko** [comment]
@Soullivaneuh I'm talking about https://github.com/sonata-project/SonataCoreBundle/blob/master/Form/EventListener/ResizeFormListener.php

**Comment by Soullivaneuh** [comment]
@nandorstanko Oh, good point! That's a mistake.

**Comment by Soullivaneuh** [comment]
Well, it's fixed.

**Comment by nandorstanko** [comment]
@Soullivaneuh Thanks! Maybe this commit fixes this https://github.com/sonata-project/SonataCoreBundle/pull/165 as well...
