### ISSUE TITLE
Datepicker issue "offset.top values are wrong in some cases"

### ISSUE THREAD

**Issue by GoZOo** [sonata-project/SonataCoreBundle#171]
Please, follow this issue : https://github.com/Eonasdan/bootstrap-datetimepicker/issues/736 since this issue apply to v3 version used by sonataCoreBundle

**Comment by GoZOo** [comment]
This issue has been commited by @Eonasdan. Please, make this available in SonataCoreBundle to https://github.com/Eonasdan/bootstrap-datetimepicker/commit/b04a8eeffaa960d6e90e1714a3eca18eef8b4a3c

**Comment by pulzarraider** [comment]
I think that the correct solution here will be to upgrade to the latest version of datetimepicker, related to sonata-project/SonataCoreBundle#149

**Comment by GoZOo** [comment]
I think this issue can take long time.

My issue has been resolved and merged in v3 branch : https://github.com/Eonasdan/bootstrap-datetimepicker/pull/1203.
There is no tags but some commits https://github.com/Eonasdan/bootstrap-datetimepicker/commits/version3

**Comment by pulzarraider** [comment]
Upgraded in #190. Thank you @GoZOo.
