### ISSUE TITLE
SonataCoreBundle assets are never used with other Sonata bundles

### ISSUE THREAD

**Issue by ltarasiewicz** [sonata-project/SonataCoreBundle#176]
Hello,
I've noticed that SonataCoreBundle isntalls many vendor assets after running `php app/console assets:install`. However, these assets are never utilized with other Sonata bundles.

E.g. I've instsalled SonataUserBundle which I believe should now rely on assets present in SonataCoreBundle. Unfortunately, no assets are ever loaded. This  `/login`  or  `/register` pages display only the HTML markup. No styles are ever applied.

How is then SonataCoreBundle integrated with other Sonata bundles?

**Comment by pulzarraider** [comment]
>  However, these assets are never utilized with other Sonata bundles.
Please see https://github.com/sonata-project/SonataAdminBundle/blob/master/DependencyInjection/Configuration.php#L282-L284 SonataCoreBundle`s assets are used at least in SonataAdminbundle.

Did you try another pages, not just the /login or /register? If your page is not working properly. please check the url of the assets.
