### ISSUE TITLE
switch from glyphicons to font-awesome

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/SonataCoreBundle#194]
here:
https://github.com/sonata-project/SonataCoreBundle/blob/a686f9bc46c47cd34ad3166fcadb612614bab48a/Form/Type/BasePickerType.php#L100

**Comment by OskarStark** [comment]
@core23 would you like to change the icons here?

**Comment by core23** [comment]
Jobs done ;) #197

**Comment by OskarStark** [comment]
awesome :+1:
