### ISSUE TITLE
Sync issue between packagist and github

### ISSUE THREAD

**Issue by BenoitLeveque** [sonata-project/SonataCoreBundle#216]
When updating my project i saw sync issue between packagist and github for 2.3.10 tag

My composer update display the following line

```
  - Installing sonata-project/core-bundle (2.3.10)
    Cloning b0663c5f1962d18126989182002412bcdec37ff4
```

Last commit in 2.3.10 tags is 44f22c8497bb8c4fbeded411ab5d0ab8d649118e

**Comment by rande** [comment]
@BenoitLeveque should be ok now : https://packagist.org/packages/sonata-project/core-bundle
