### ISSUE TITLE
Wrong service resolution in form extension

### ISSUE THREAD

**Issue by sagikazarmark** [sonata-project/SonataCoreBundle#217]
There is an error when trying to reach the API doc page:

`Notice: Undefined index: sonata_user_api_form_group`

I traced back the problem to [this](https://github.com/sonata-project/SonataCoreBundle/blame/master/Form/Extension/DependencyInjectionExtension.php#L90) line.

The problem is that the FQCN is identified by the service name and the service is resolved by the classname. By the time the extension gets to the `sonata_user_api_form_group` service, the FQCN is already resolved with `sonata_user_api_form_user` name in it.

Since Symfony 3 encourages to use class name, the given class could be extended and unique classes could be created instead.

The issue occured with admin and user bundle installed, but I guess this affects many other bundles as well.

[EDIT By Maintainer]
- [x]  NotificationBundle
- [x]  MediaBundle
- [x]  NewsBundle
- [x]  UserBundle
- [x]  PageBundle
- [x]  ecommerce

**Comment by sagikazarmark** [comment]
Ping @rande @Soullivaneuh @OskarStark

**Comment by rande** [comment]
Are you using Symfony3 ?

**Comment by sagikazarmark** [comment]
No, 2.8

**Comment by rande** [comment]
Yep, you should stick to 2.7 with Sonata's bundle for now. Here the status of Sonata's bundles: https://docs.google.com/spreadsheets/d/1fSpS10nzlEj9HE-GdZ-BHcxileEzHwRIzLlNfdNtZ2k/edit#gid=0&vpid=C4

**Comment by sagikazarmark** [comment]
Thanks for letting me know.

But the issue is still valid, and points to a valid problem, isn't it?

**Comment by rande** [comment]
Yes, we need to do similar code on sonata's bundles: https://github.com/sonata-project/SonataClassificationBundle/commit/b67092a2b85414c1936ce50602f313f771a0ad8a

**Comment by sagikazarmark** [comment]
Thanks.

One more thing related to UserBundle: is a bit special, because we have the FOS User serialization mapping added manually.

This is my config:

``` php
jms_serializer:
    metadata:
        auto_detection: true
        directories:
            FOSUB:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.storage_dir%/vendor/sonata-project/user-bundle/Resources/config/serializer/FOSUserBundle"
#                path: "@SonataUserBundle/Resources/config/serializer/FOSUserBundle"
```

And I get this error:

Expected argument of type "string, Symfony\Component\Form\ResolvedFormTypeInterface or Symfony\Component\Form\FormTypeInterface", "NULL" given (here: `/opt/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php line 74`).

If I remove the serializer config (which I copied from the sandbox, modified  bit) the error is gone, but username and other fields are missing from the form.

**Comment by rande** [comment]
Can paste the stack trace somewhere ? All edge cases are not yet tested .

**Comment by sagikazarmark** [comment]
Sure.

Stack trace:
http://pastebin.com/QipGYDPp

Log:
http://pastebin.com/0NecRcRk

**Comment by rande** [comment]
I guess, something is missing here:

```
   at Symfony\Component\Form\FormFactory->create(null, null, array('block_name' => 'entry'))
        in /opt/symfony/vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Parser/FormTypeParser.php line 168
```

**Comment by sagikazarmark** [comment]
Yeah, that first parameter should not be null, a form type os awaited there I think. I can't decide that adding JMS Serializer config at all is the problem, or this FOS config specifically screws something up.

**Comment by jordisala1991** [comment]
This issue seems solved. Feel free to ping me if this is not the case.
