### ISSUE TITLE
form.type_extension.form.data_collector only available in debug with Symfony 2.8

### ISSUE THREAD

**Issue by jocel1** [sonata-project/SonataCoreBundle#218]
Hi,

In SonataCoreBundle.php you register 'form.type_extension.form.data_collector', but in Symfony 2.8 the service is registered only in debug environment, through the form_debug.xml.
When I enable the prod mode, I get:

> request.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "form.type_extension.form.data_collector". Did you mean one of these: "form.type_extension.form.http_foundation", "form.type_extension.form.validator"?" at /Users/jocelynfournier/Documents/workspace/daphni/app/bootstrap.php.cache line 2181 {"exception":"[object](Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException%28code: 0%29: You have requested a non-existent service "form.type_extension.form.data_collector". Did you mean one of these: "form.type_extension.form.http_foundation", "form.type_extension.form.validator"? at /Users/jocelynfournier/Documents/workspace/daphni/app/bootstrap.php.cache:2181)"} []

I have to manually redeclare the services to have it work properly again.

BR,
  Jocelyn Fournier

**Comment by OskarStark** [comment]
could you please provide a PR with a fix for this bug?

**Comment by magedan** [comment]
Confirm same error in prod mode.
Also, got similar error in dev mode:
> Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "mopa_bootstrap.form.type_extension.help"." at vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php line 303 

(I don't use MopaBootstrapBundle in my current project)

Bundles installed: Symfony 2.8.1, SonataCoreBundle 2.3.10, SonataAdminBundle dev-master.

**Comment by IwfY** [comment]
I get the same output as magedan.

**Comment by jocel1** [comment]
@OskarStark : I have not a fix, only a dirty workaround:
in services.yml, I put :

<addr>
parameters:
    form.resolved_type_factory.data_collector_proxy.class: Symfony\Component\Form\Extension\DataCollector\Proxy\ResolvedTypeFactoryDataCollectorProxy
    form.type_extension.form.data_collector.class: Symfony\Component\Form\Extension\DataCollector\Type\DataCollectorTypeExtension
    data_collector.form.class: Symfony\Component\Form\Extension\DataCollector\FormDataCollector
    data_collector.form.extractor.class: Symfony\Component\Form\Extension\DataCollector\FormDataExtractor

services:
    273c3613ab6d0c30d76b02f55c01349fc6c9f5a3e8dbb38e53fab007ac779f42_1:
        class: %form.resolved_type_factory.class%
        public: false
    form.resolved_type_factory:
        class: %form.resolved_type_factory.data_collector_proxy.class%
        arguments: ['@273c3613ab6d0c30d76b02f55c01349fc6c9f5a3e8dbb38e53fab007ac779f42_1', '@data_collector.form']
    form.type_extension.form.data_collector:
        class: %form.type_extension.form.data_collector.class%
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType, extended-type: Symfony\Component\Form\Extension\Core\Type\FormType }
        arguments: ['@data_collector.form']
    data_collector.form.extractor:
        class: %data_collector.form.extractor.class%
    data_collector.form:
        class: %data_collector.form.class%
        tags:
            - { name: data_collector, template: '@WebProfiler/Collector/form.html.twig', id: form, priority: 310 }
        arguments: ['@data_collector.form.extractor']
</addr>

**Comment by IwfY** [comment]
If there is code that references MopaBootstrapBundle resources, it should be added to the composer.json requirements section.

**Comment by RuslanBahlai** [comment]
Hi there, I fixed problem by removing "vendor" folder, and updating it with composer again

**Comment by jordisala1991** [comment]
Without more information this is hard to debug and/or reproduce. Closing for now, if you think this is still relevant, ping me with more information about this issue
