### ISSUE TITLE
Update Bootstrap 3 Datepicker version

### ISSUE THREAD

**Issue by peter-gribanov** [sonata-project/SonataCoreBundle#219]
Actualize version for [Bootstrap 3 Datepicker](https://github.com/Eonasdan/bootstrap-datetimepicker). Last release 4.17.37 on 10 Sep 2015.

Incorrect time picker from _sonata_type_datetime_picker_

``` php
$formMapper->add('duration', 'sonata_type_datetime_picker', [
    'label' => 'Продолжительность',
    'required' => false,
    'format' => 'HH:mm:ss',
    'date_format' => 'HH:mm:ss'
]);
```

![Time picker](https://habrastorage.org/files/c14/cbd/6ce/c14cbd6ce0cd4cd1b70b19d756b885e3.png)

**Comment by OskarStark** [comment]
is this just a reminder ticket?
do you have a problem?

i don't understand the goal of this ticket

**Comment by peter-gribanov** [comment]
The problem is that creating a field to select only time we can see a calendar for date selection. The date can not be selected, but the calendar is still visible. It should not be.
Will better show only [time picker](http://eonasdan.github.io/bootstrap-datetimepicker/#custom-formats)

**Comment by MAXakaWIZARD** [comment]
Actually there is a PR already: #149 
And it is targeted to version `3.0`, because there will be BC breaks.

**Comment by jordisala1991** [comment]
Someone could continue this one : https://github.com/sonata-project/SonataCoreBundle/pull/149

**Comment by core23** [comment]
We will find a new way for assets (Refs https://github.com/sonata-project/SonataCoreBundle/pull/570)

This project will be deprecated soon. Please fill a new issue in the https://github.com/sonata-project/twig-extensions project, after the split
