### ISSUE TITLE
Attempted to load interface "DomainObjectInterface" Symfony3 and SonataCoreBundle master

### ISSUE THREAD

**Issue by EmixMaxime** [sonata-project/SonataCoreBundle#221]
Hello guys,
I have a problem, error : 
ClassNotFoundException in Admin.php line 56:
Attempted to load interface "DomainObjectInterface" from namespace "Symfony\Component\Security\Acl\Model".
Did you forget a "use" statement for another namespace?

I use Symfony3 and sonata-project/admin-bundle dev-master

**Comment by nkl90** [comment]
I have some problem. How fix it?

**Comment by core23** [comment]
Please update your dependencies. Looks like you have a problem with the **SonataAdminBundle** not the **SonataCoreBundle**.
