### ISSUE TITLE
[WIP] Use the same labels across bundles

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataCoreBundle#229]
We should sync the labels across all bundles and use them to get more efficient. I think the https://github.com/sonata-project/SonataAdminBundle/labels are a good base, because it has the most tickets and labels.

@OskarStark mentioned this tools which could help us:
https://github.com/Jimdo/github-sync-labels-milestones
https://github.com/piwik/github-sync

In general: IMO we should create a developer repository where we store global configurations and talk about general things, like supported version, travis usage, milestones, etc ....

Please raise your voice @sonata-project/contributors

**Comment by dbu** [comment]
+1

**Comment by OskarStark** [comment]
:+1: for the labels

what about using [Slack.com](https://slack.com/) for communication?

**Comment by core23** [comment]
:+1: slack could be a good start

**Comment by Th3Mouk** [comment]
@OskarStark :+1:

**Comment by OskarStark** [comment]
@Th3Mouk you can send me your mailadress via twitter and i will invite you, if you are inetrested in joining us on slack.com

**Comment by OskarStark** [comment]
- Bug
- Easy Pick
- Doc
- Critical
- In progress
- Pending user reply
- Major-Version
- Minor-Version
- Patch-Version
- Review required
- hasPR
- Vendor
- Questions
- Nice to have
- Must have
- Need Confirmation

these are the labels from the SonataAdminBundle and i would like to use them across the project.
Should we add some new ones?

**Comment by Th3Mouk** [comment]
@OskarStark i can't send you a PM on twitter, you got my email on my Github profile thx

**Comment by OskarStark** [comment]
thank you, done

**Comment by core23** [comment]
IMO patch, minor and major version are needless, we have milestones for this

**Comment by OskarStark** [comment]
fine for me

**Comment by core23** [comment]
Closing this in favor of https://github.com/sonata-project/dev-kit/issues/20
