### ISSUE TITLE
BooleanType choices are broken

### ISSUE THREAD

**Issue by dVaffection** [sonata-project/SonataCoreBundle#231]
I refer to the line [59](https://github.com/sonata-project/SonataCoreBundle/blob/master/Form/Type/BooleanType.php#L59)
According so [Symfony docs](http://symfony.com/doc/current/reference/forms/types/choice.html#choices) 

> The choices option is an array, where the array key is the item's label and the array value is the item's value

They work if they are flipped:
```php
'choices'            => array(
    'label_type_yes' => self::TYPE_YES,
    'label_type_no' => self::TYPE_NO,
),
```

**Comment by greg0ire** [comment]
See #228
