### ISSUE TITLE
#238 PR typo

### ISSUE THREAD

**Issue by fracsi** [sonata-project/SonataCoreBundle#241]
#238 tried to make the CoreBundle SF3 compatible, but there is a typo at: [BooleanType:L84](https://github.com/sonata-project/SonataCoreBundle/blob/363b3fe289a4244d98168486bc3b4b74baa8536f/Form/Type/BooleanType.php#L84)

The `choices_as_value` key is invalid, the option is called: `choices_as_values`

**Comment by greg0ire** [comment]
Can you make a PR to fix that?

**Comment by fracsi** [comment]
PR #242

**Comment by OskarStark** [comment]
Thank you @fracsi
