### ISSUE TITLE
Boolean Filter Broken in SonataAdmin

### ISSUE THREAD

**Issue by hug963** [sonata-project/SonataCoreBundle#258]
After updating the sonata core bundle to 2.3.11 boolean filter fields in sonata Admin are broken.
The field displays 1 and 2 instead of yes and no, and the filter doesn't work.
Downgrading to 2.3.10 fixes the issue.
I'm using Symfony 2.8.6.

![sonatacore_field_boolean](https://cloud.githubusercontent.com/assets/6074980/15216819/92f0ae1e-1850-11e6-9895-1f7fdab6f72d.png)

**Comment by greg0ire** [comment]
Thanks a lot for reporting that! Could you have a look at the history of the boolean filter class ? I think someone might have touched that lately, especially regarding how and when the `choices_as_values` is used.

**Comment by greg0ire** [comment]
See #238

**Comment by greg0ire** [comment]
Wait, sadly, the 2.x branch is not maintained anymore, so you should consider upgrading to 3.x, and see if the problem is still there if you want us to take a look at it

**Comment by Soullivaneuh** [comment]
> Wait, sadly, the 2.x branch is not maintained anymore, so you should consider upgrading to 3.x, and see if the problem is still there if you want us to take a look at it

Or stay on 2.3.10. 2.3.11 was pushed because of trailling commit on the old and removed `2.3` branch.

**Comment by hug963** [comment]
I can't update to 3.x at the moment as I'm using Sonata User Bundle.
"sonata-project/user-bundle 2.2.4 requires sonata-project/admin-bundle ~2.2,>=2.2.9".

I'll just stay on 2.3.10 for now.

Thanks.

**Comment by Soullivaneuh** [comment]
@hug963 Yes, migration is not terminated.

**Comment by jdeveloper** [comment]
I have the same prome. I can't change to version 3.x because I am using SonataUserBundle.

I downgraded SonataCoreBundle and SontaAdminBundle, both, to version 2.3.10 but it doesn't work.

Some suggestion?

**Comment by greg0ire** [comment]
> Some suggestion?

Triple check. It worked for me.

**Comment by ernestocuzcueta** [comment]
HI
Can you explain what is "Triple check"
Thanks

**Comment by greg0ire** [comment]
Triple check = check again

**Comment by binzram** [comment]
> greg0ire commented on May 12
> See #238

[This one](https://github.com/sonata-project/SonataCoreBundle/commit/ccdb1c5d8fcf5c93ae1e643dea1d7d26510de8ab) resolves the issue and the fixes your problem in v2.x @hug963.
