### ISSUE TITLE
Inject formats in BaseSerializerHandler

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/SonataCoreBundle#306]
### Environment

Not relevant

## Subject

The BaseSerializerHandler has [formats hardcoded in it](https://github.com/sonata-project/SonataCoreBundle/blob/3.x/Serializer/BaseSerializerHandler.php#L43). This should be changed with injection through a method with the following signature : `public static function setFormats`. The injection should be optional and default to the current values (json, xml, and yml).

The issue was discovered [here](https://github.com/sonata-project/SonataCoreBundle/pull/303#discussion_r67187167), thanks to @ahmetakbn new tests, which should be simplified in the same PR.

**Comment by ahmetakbn** [comment]
@greg0ire I will handle this change, thanks.

**Comment by greg0ire** [comment]
Thank **you**
