### ISSUE TITLE
Problem with boolean in filter

### ISSUE THREAD

**Issue by bartosz-malec** [sonata-project/SonataCoreBundle#317]
I have problem with boolean field type in filters. I use 2.3.11 SonataCoreBundle version.

I attached image which describes whats wrong: 
![boolean](https://cloud.githubusercontent.com/assets/13161733/16371386/8cf21ff6-3c46-11e6-838d-14e5579073c1.png). 

In html we have:
```html
<option value="label_type_yes">1</option>
<option value="label_type_no">2</option>
```

**Comment by Soullivaneuh** [comment]
Issue already reported AFAIK.

The 2.x branch is not maintained anymore, please upgrade to 3.x.

The 2.3.11 tag was pushed to keep the work made after 2.3.10 before new major release tag.

If 2.3.11 is buggy for you and if you can't go to 3.x right now, please fallback to 2.3.10.

**Comment by bartosz-malec** [comment]
Yes, back to 2.3.10 helps.
