### ISSUE TITLE
Choice values not translated for list and show fields when ChoiceType::class is used

### ISSUE THREAD

**Issue by aurelijusrozenas** [sonata-project/SonataCoreBundle#359]
#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.9.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.2.0 Symfony SonataBlockBundle
sonata-project/cache                     1.0.7 Cache library
sonata-project/core-bundle               3.1.1 Symfony SonataCoreBundle
sonata-project/doctrine-orm-admin-bundle 3.1.1 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.7.0 Lightweight Exporter library
```

#### Symfony packages

```bash
$ composer show symfony/*
symfony/assetic-bundle     v2.8.0  Integrates Assetic into Symfony2
symfony/monolog-bundle     2.11.1  Symfony MonologBundle
symfony/phpunit-bridge     v2.8.4  Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.1.1  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.1.1  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.1.1  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.1.1  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.1.1  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.1.1  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.1.1  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.1.1  Symfony utilities for portability of PHP codes
symfony/security-acl       v2.8.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.3.11 Symfony SwiftmailerBundle
symfony/symfony            v2.8.4  The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
HP 5.6.28-1+deb.sury.org~xenial+1 (cli) 
```

## Subject
I am updating admins to future proof choice arrays with `'choices_as_values' => true`. Form fields and Datagrid filter fields - works as expected. Now show and list fields - not so much, found the following:
1. `'choices_as_values' => true,` is ignored. Whether added or not, does change the ouput.
2. For field type, `'choice'` - translates values back from array, but `\Symfony\Component\Form\Extension\Core\Type\ChoiceType::class` - does not.

## Working code
```php
protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add(
                'type',
                \Symfony\Component\Form\Extension\Core\Type\ChoiceType::class,
                [
                    'choices' => self::getTypeChoices(),
                    'choices_as_values' => true,
                ]
            )
        ;
    }

    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add(
                'type',
                null,
                [],
                \Symfony\Component\Form\Extension\Core\Type\ChoiceType::class,
                [
                    'choices' => self::getTypeChoices(),
                    'choices_as_values' => true,
                ]
            )
        ;
    }

    protected function configureShowFields(ShowMapper $showMapper)
    {
        $showMapper
            ->add(
                'type',
                'choice',
                [
                    'choices' => array_flip(self::getTypeChoices()),
                ]
            )
        ;
    }

    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->add(
                'type',
                'choice',
                [
                    'choices' => array_flip(self::getTypeChoices()),
                ]
            )
        ;
    }

    protected static function getTypeChoices()
    {
        $choices = [
            'Hey, the option!' => self::OPTION_NO_1,
        ];

        return $choices;
    }
```

## Non-working code

```php
protected function configureShowFields(ShowMapper $showMapper)
    {
        $showMapper
            ->add(
                'type',
                \Symfony\Component\Form\Extension\Core\Type\ChoiceType::class,
                [
                    'choices' => self::getTypeChoices(),
                    'choices_as_values' => true,
                ]
            )
        ;
    }

    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->add(
                'type',
                \Symfony\Component\Form\Extension\Core\Type\ChoiceType::class,
                [
                    'choices' => self::getTypeChoices(),
                    'choices_as_values' => true,
                ]
            )
        ;
    }
```

## Steps to reproduce
Using `Non-working code`, `ChoiceType::class` for type and `'choices_as_values' => true` option.

## Expected results
I would expect to same values for form, filter, show and list fields as it is when using `'choice'` for type and `'choices_as_values' => false` option.

## Actual results
String is translated for form and filter fields, but not for show and list.
Tried upgrading to symfony 3.0.9. Removed `choices_as_values`. Same result.

**Comment by greg0ire** [comment]
What does the profiler say about it? Was there a failed attempt to translate the values, and if yes, in which catalog?

**Comment by aurelijusrozenas** [comment]
No, nothing about translating the value.

**Comment by greg0ire** [comment]
What if you specify a 'translation_domain' option? Does the profiler show an attempt to translate values?

**Comment by aurelijusrozenas** [comment]
No, nothing. But should profiler display any messages about translations for choice values? I think I might described my problem incorrectly, because I am not using translation files for this, just choices array. In the form view, where this is working, I see in profiler that message was already replaced when it came to translator. In show view, profiler does not show any attempts to translated the key.

**Comment by greg0ire** [comment]
> But should profiler display any messages about translations for choice values?

Well yeah. It does for the form view, right? So why not for the show view?

Maybe you could try to debug [this line](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Resources/views/CRUD/list_choice.html.twig#L44). I see there is a `catalogue` option :confused:

**Comment by aurelijusrozenas** [comment]
The problem is in [these lines](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Resources/views/CRUD/list_choice.html.twig#L56-L62). It tries to find `field_description.options.choices[value]` but of course the array is now flipped and value cannot be found.

For problem 2. - when I use `ChoiceType::class` instead of `'choice'`, `show_choice.html.twig` template is never included, only `base_show_field.html.twig`.

**Comment by greg0ire** [comment]
Maybe it has to do with [this mapping](https://github.com/sonata-project/SonataAdminBundle/blob/240ecbd02d453f9acaf81e00112ff5d8dae4459b/DependencyInjection/AbstractSonataAdminExtension.php#L76)…

**Comment by greg0ire** [comment]
Not sure it makes sense to use `ChoiceType::class` here… not everything maps to a form type, for instance `trans` doesn't.

**Comment by aurelijusrozenas** [comment]
Yes, the mapping is the cause for not including template. So conclusion here is not to use full class names from symfony for admin forms?
Back to the 1. problem, it seems functionality for symfony 3 flipped choices is unimplemented. Do you think I should close this issue and create new one with information regarding that problem only?

**Comment by greg0ire** [comment]
> So conclusion here is not to use full class names from symfony for admin forms?

Well, these are not forms, are they?

> Back to the 1. problem, it seems functionality for symfony 3 flipped choices is unimplemented. Do you think I should close this issue and create new one with information regarding that problem only?

Yes please create a new one, it will make it easier for people who want to join this discussion to understand things, there is already a bit much to read if you want to. Let's keep things focused.
