### ISSUE TITLE
Eonasdan datepicker missing options

### ISSUE THREAD

**Issue by RomainSanchez** [sonata-project/SonataCoreBundle#373]
Hi, i wanted to know if there is any plan to add the missing options (like viewMode, inline, ...) for the datepicker to `BasePickerType`. 

I am willing to do it myself and make a PR if needed.

May be related to #149 

http://eonasdan.github.io/bootstrap-datetimepicker/Options/

**Comment by greg0ire** [comment]
I don't know if there are any plans, but do feel free to make a PR.

**Comment by RomainSanchez** [comment]
I added and tested all missing options except keyBinds http://eonasdan.github.io/bootstrap-datetimepicker/Options/ as it seems pretty dirty to add that chunk of javascript to php code.

Time related options were added to `DateTimePickerType` while all others were added to `BasePickerType`

CONTRIBUTING.md confused me a bit, should i provide tests and documentation in the PR ?

**Comment by greg0ire** [comment]
> CONTRIBUTING.md confused me a bit, should i provide tests and documentation in the PR ?

You should always try to, yes.

> I added and tested all missing options except keyBinds http://eonasdan.github.io/bootstrap-datetimepicker/Options/ as it seems pretty dirty to add that chunk of javascript to php code.

Please try avoiding js in php or twig. If you need to pass data from php to js, please use data attributes to store the data in the dom, then get that data in js.

**Comment by RomainSanchez** [comment]
> Please try avoiding js in php or twig. If you need to pass data from php to js, please use data attributes to store the data in the dom, then get that data in js.

If you look at this option it is the full js code of the key events, that's why i didn't add it as i wouldn't see such a chunk of code in a data attribute.

**Comment by greg0ire** [comment]
How about allowing specifying sth like : 

```
['keyBinds' => [
   'up' => 'name.of.my.custom.js.function',
   'down' => 'name.of.another.custom.js.function',
]
```

and then in twig : `data-up-function="name.of.my.custom.js.function" data-down-function="you.get.the.idea"` ?

**Comment by RomainSanchez** [comment]
As it turns out the keyBinds option is only available in 4.x and sonata 3.x uses 3.1.3 so problem solved for now.
I guess we will have to tackle that after #149 has been merged.

Do you think i should keep on with this or wait for #149 to be merged so i can start over from a clean state ?

**Comment by greg0ire** [comment]
> As it turns out the keyBinds option is only available in 4.x and sonata 3.x uses 3.1.3 so problem solved for now.

I'm not sure #149 will ever get merged, it looks pretty inactive.
I think you should keep on with the rest, and if you feel up to it, carry #149 yourself first.

**Comment by RomainSanchez** [comment]
Ok i'll see what i can do

**Comment by RomainSanchez** [comment]
I just added the missing options (3) for now as it is BC and #149 isn't
