### ISSUE TITLE
Doctrine manager error

### ISSUE THREAD

**Issue by jerni** [sonata-project/SonataCoreBundle#38]
Got this error when running web console bundle

FatalErrorException: Compile Error: Cannot redeclare class Sonata\CoreBundle\Entity\DoctrineBaseManager in vendor\sonata-project\core-bundle\Sonata\CoreBundle\Entity\DoctrineBaseManager.php line 23

**Comment by core23** [comment]
Does the problem still exist? @jerni

**Comment by joseph-stalin-o-erni** [comment]
Hi @core23 ,

Issue is already fixed. :)

Thanks

**Comment by OskarStark** [comment]
Thanks for the feedback @joseph-stalin-o-erni
