### ISSUE TITLE
Message tooltip (for a datetime attribute constraint) doesnt appear

### ISSUE THREAD

**Issue by benjellounayoub** [sonata-project/SonataCoreBundle#39]
Creating a custom constraint on a datetime field works like a charm, but the tooltip message cannot be displayed after a mouse over the same field (like it does with other field types), maybe the JQuery selector of this toogle behavior does'nt support the select/options type (unlike inputs, checkoxes and other available widget types) ...

**Comment by core23** [comment]
Does the problem still exist?

**Comment by BenoitLeveque** [comment]
i think your mean @benjellounayoub not me, i don't know what is that issue ?

**Comment by core23** [comment]
Sorrry for distdurbing you :smile:

@benjellounayoub Any news for this

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.
