### ISSUE TITLE
ResizeFormListener preSubmit empty rows removal problem

### ISSUE THREAD

**Issue by PapsOu** [sonata-project/SonataCoreBundle#408]
#### Sonata packages

```bash
$ composer show sonata-project/\*
sonata-project/admin-bundle              3.x-dev 300b915 The missing Symfony Admin Generator
sonata-project/block-bundle              3.x-dev a50efa5 Symfony SonataBlockBundle
sonata-project/cache                     1.x-dev efc45b4 Cache library
sonata-project/core-bundle               3.x-dev 8feea86 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.x-dev bb71f86 Symfony SonataDatagridBundle
sonata-project/doctrine-orm-admin-bundle 3.x-dev ab4a06d Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.x-dev 7f707f2 Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.x-dev 2b352df Lightweight Exporter library
sonata-project/intl-bundle               2.x-dev 9464c30 Symfony SonataIntlBundle
```

#### Symfony packages

```bash
$ composer show symfony/\*
symfony/assetic-bundle     dev-master 0241b13 Integrates Assetic into Symfony2
symfony/monolog-bundle     dev-master c9fb33a Symfony MonologBundle
symfony/phpunit-bridge     3.4.x-dev 5a6688a  Symfony PHPUnit Bridge
symfony/polyfill-iconv     dev-master ae1347f Symfony polyfill for the Iconv extension
symfony/polyfill-intl-icu  dev-master 3191cbe Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  dev-master f29dca3 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     dev-master bc0b7d6 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     dev-master 032fd64 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      dev-master ebccbde Symfony utilities for portability of PHP codes
symfony/security-acl       dev-master 3bf313c Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.2             Symfony SwiftmailerBundle
symfony/symfony            3.2.x-dev c0486f6  The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
PHP 7.1.6-1~ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jun  9 2017 08:26:34) ( NTS )
```

## Subject

ResizeFormListener preSubmit removes all dynamic fields created on a PRE_SET_DATA event by updating entity's collections

## Steps to reproduce

On pre_set_data event, add items in entity's collection (like an EAV structure)
Submit the form with an intentional error (a duplicate non unique field value on the entity itself)

## Expected results

The form should have correct EAV form items

## Actual results

The form have the last EAV item repeated

While digging deeper, I've seen that ResizeFormListener::preSubmit method removes all children fields of the current form whitout any check.

`vendor/sonata-project/core-bundle/Form/EventListener/ResizeFormListener.php:157`
```php
        // Remove all empty rows except for the prototype row
        foreach ($form as $name => $child) {
            $form->remove($name);
        }
```

When commenting out `$form->remove($name);`, the form is correctly built.

Is there a way to avoid this removing ?

EDIT: Here the entity EAV model :
![eav](https://user-images.githubusercontent.com/5792207/27086444-7dddda34-5052-11e7-94b7-f1a9aa3c1934.png)

**Comment by PapsOu** [comment]
The solution is there : https://stackoverflow.com/questions/44538483/sonata-type-collection-is-cleared-on-presubmit

The option « modifiable » solve the problem (but I don't find it in the sonata_type_collection documentation).

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed.
