### ISSUE TITLE
Upgrading Javascript vendors

### ISSUE THREAD

**Issue by Mindsers** [sonata-project/SonataCoreBundle#431]
I have a problem with javascript dependencies in the sonata project. Today i want to use javascript libraries to develop some parts of my sonata/symfony project.

Problem : I have conflict between my imports using webpack and the sonata manual imports. Some libraries provided by sonata is 2 years old... Those old versions aren't available in ComonJS/RequireJS/UMD/AMD/ES6 format and I can't import them. So I imported recent versions but this results in unexpected behaviors.

I create this issue to find at least a temporary solution and help to improve sonata. :)

**Comment by Soullivaneuh** [comment]
Bug with another provided vendor than your are not officially supported, we can support each user env.

However, if you want to propose vendor upgrade on sonata with a BC way, feel free to open PR.

I close this issue as it's not specific nor supported.

Best regards.

**Comment by Mindsers** [comment]
Thanks.
