### ISSUE TITLE
Could not load type "sonata_type_color" only works with class name

### ISSUE THREAD

**Issue by AntonioCS** [sonata-project/SonataCoreBundle#438]
#### Sonata packages
sonata-project/block-bundle              3.4.0              3.4.0              Symfony SonataBlockBundle
sonata-project/cache                     1.0.7              1.0.7              Cache library
sonata-project/core-bundle               3.5.1              3.5.1              Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1              2.2.1              Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2              1.0.2              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.7              3.1.7              Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.2.0              2.2.0              Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1              1.7.1              Lightweight Exporter library
sonata-project/user-bundle               dev-master a962eaa dev-master a962eaa Symfony SonataUserBundle

#### Symfony packages

symfony/monolog-bundle     v3.1.0 v3.1.1  Symfony MonologBundle
symfony/phpunit-bridge     v3.3.9 v3.3.10 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.5.0 v1.5.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.5.0 v1.5.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.5.0 v1.5.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.5.0 v1.5.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.5.0 v1.5.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.5.0 v1.5.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0 v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.3 v3.1.0  Symfony SwiftmailerBundle
symfony/symfony            v3.3.9 v3.3.10 The Symfony PHP framework
#### PHP version

PHP 7.1.8-2+ubuntu16.04.1+deb.sury.org+4 (cli) (built: Aug  4 2017 13:04:12) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.8-2+ubuntu16.04.1+deb.sury.org+4, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

## Subject

Could not load type "sonata_type_color"

I have an admin class and inside the configureFormFields method I have the following

```
        $formMapper
    //other fields
            ->add('colour', 'sonata_type_color')
```
Now when I go to the page of the form I get the exception:

![image](https://user-images.githubusercontent.com/1086401/31274158-b02e2f2a-aa89-11e7-8a7d-b655fce669b2.png)

I have done the setup steps (https://sonata-project.org/bundles/core/master/doc/reference/form_types.html#sonata-type-color-picker)
I can see the ColorType in the vendor folder.

I did get this working by using ColorType::class

**Comment by OskarStark** [comment]
This is not an error, as you are using Sf 3, you need to use FQCN's instead of the form type name

**Comment by AntonioCS** [comment]
![image](https://user-images.githubusercontent.com/1086401/31274794-5ecb7c16-aa8c-11e7-8353-b63278ef032b.png)

Maybe update the documentation?

**Comment by AntonioCS** [comment]
I am reading the master version of the documentation.

**Comment by OskarStark** [comment]
@greg0ire am I wrong?

**Comment by AntonioCS** [comment]
@OskarStark You are correct as I have used the FQCN and it worked but please do update the documentation.

**Comment by greg0ire** [comment]
@AntonioCS can you please make a PR to update the docs?

**Comment by AntonioCS** [comment]
@greg0ire In less than 5m @OskarStark closed my issue. I am sure if he stops watching the issues so attentively he will have time to do a PR to update the docs.

**Comment by OskarStark** [comment]
1) I was wrong, as this is an issue, as other names like `text` or `choice` still work
2) the docs are correct 👍 
3) please save your time to create a PR which fixes the docs

>@OskarStark closed my issue. I am sure if he stops watching the issues so attentively he will have time to do a PR to update the docs.

of course, this is how open source works 😄

**Comment by greg0ire** [comment]
> In less than 5m @OskarStark closed my issue.

I'm sure he didn't mean it as an insult.

> I am sure if he stops watching the issues so attentively he will have time to do a PR to update the docs.

I'm a bit like him, sometimes I close things too hastily, because I don't want the repository to be even more cluttered. I reopen when told wrong, not a big deal. Please be kind with us, and consider making the PR, it would be very appreciated.

**Comment by greg0ire** [comment]
Looks like it was a bug after all. @AntonioCS, please test #439 (and thank the very kind author).
