### ISSUE TITLE
Remove FormHelper component

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataCoreBundle#440]
We should remove the `FormHelper` component, because it is an interal component and it is only a dirty hack to allow form aliases in symfony 3+.

Not sure if we can do this on a stable branch...

**Comment by greg0ire** [comment]
> Not sure if we can do this on a stable branch...

- not until we drop old sf versions
- even then, it would be a huge BC-break, what we should do is detect usage of non-FQCNs and throw deprecations.

**Comment by jordisala1991** [comment]
Removed on master: https://github.com/sonata-project/SonataCoreBundle/pull/536

Closing for now, if you think this should be handled on stable too, please reopen.
