### ISSUE TITLE
Update dependency cocur/slugify to 3.x to support new languages

### ISSUE THREAD

**Issue by marcelorodrigo** [sonata-project/SonataCoreBundle#447]
### Environment

- Symfony 3.3.x fresh installation
- SonataAdminBundle
- SonataDoctrineORMAdminBundle

#### Sonata packages
```
$ composer show --latest 'sonata-project/*'
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
```

#### PHP version

```
$ php -v
PHP 7.1.8 (cli) (built: Aug  1 2017 20:56:53) ( ZTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.8, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.4, Copyright (c) 2002-2017, by Derick Rethans
```

## Subject
Update cocur/slugify to v3.x to support Brazilian Portuguese Rules (plus Hungarian and missing French and Persian rules)

## Steps to reproduce
- Fresh install of symfony 3.3.x
- Install SonataAdminBundle
- Install SonataDoctrineORMAdminBundle
- Try to require cocur/slugify 3.x version

**Comment by core23** [comment]
Can you provide a PR which will support the latest slugify version? @marcelorodrigo

**Comment by marcelorodrigo** [comment]
@core23 my bad.
Here it is #448
