### ISSUE TITLE
InlineConstraint should not overwrite __sleep ?

### ISSUE THREAD

**Issue by Hanmac** [sonata-project/SonataCoreBundle#487]
with Symfony 3.4 now i get the following warning:

> The "Symfony\Component\Validator\Constraint::__sleep()" method is considered internal This method may be replaced by an implementation of *` {@link \Serializable}` in the future. Please don't use or * overwrite it. It may change without further notice. You should not extend it from "Sonata\CoreBundle\Validator\Constraints\InlineConstraint"

i don't know the inner use of this InlineConstraint and about serializeable 

PS: i don't know why i didn't get the warning sooner because it looked like the changes where both more than 3 years old

**Comment by greg0ire** [comment]
It was introduced in 284c815085b217fc122bcd5c33a9614875ec7a3b

**Comment by Hanmac** [comment]
@greg0ire thanks, i just wonder why i didn't got the warning before.

should we try to use Serializeable or can't we do anything about it?

**Comment by greg0ire** [comment]
Right now I'm trying to find the docs on the website to understand why this would be needed.

**Comment by greg0ire** [comment]
This will do I guess: https://github.com/sonata-project/SonataCoreBundle/blob/3.x/docs/reference/conditional_validation.rst

**Comment by OskarStark** [comment]
Any news on this @Hanmac ?

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to reopen if this error still exists.
