### ISSUE TITLE
[Feature request] CSV export options

### ISSUE THREAD

**Issue by nixoschu** [sonata-project/SonataCoreBundle#50]
Situation
=======

Currently the ``Sonata\CoreBundle\Exporter\Exporter`` does not have any options for the column delimiter or the enclosing character if ``$format = csv`` is used.
Instead its using the following hardcoded:

``$writer      = new CsvWriter('php://output', ',', '"', "", true, true);``

Use Case
========
Theoretically the file is a correct CSV-File using comma as seperator but
opening a CSV-File generated by this exporter under Windows with Mircosoft Excel can cause that Excel does not manage to separate the columns correctly (depends on the OS system configurations and/or the Excel version and its configuration)

Prospect
=======
The exporter should have another param for the ``getResponse`` method which could be called ``$formatOptions``. That could be an array of options for the selected export format. That would imply that the SonataAdminBundle needs to be adjusted as well and provide the configured values for the exported format.

It seems that CSV is the only export format that needs  to be configureable at the moment. This makes it quite difficult for me to suggest where the best place would be to set up the options for the CSV export.

Admin class ?
config.yml ?
both ?

**Comment by greg0ire** [comment]
Hey! 2 years late, but I worked on that :)
