### ISSUE TITLE
Move assets to a NPM package

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/SonataCoreBundle#528]
Instead of doing a hard copy of all assets, we should make npm packages with correct requirements for each bundle using assets files.

Of course, a documentation should be provided to show how to setup the asset. We should based our sample with a symfony/encore configuration.

**Comment by jordisala1991** [comment]
This sounds like an issue for dev-kit, several bundle will need this afaik

**Comment by greg0ire** [comment]
It also sounds like an existing issue.

**Comment by greg0ire** [comment]
See https://github.com/sonata-project/dev-kit/issues/387

**Comment by Soullivaneuh** [comment]
https://github.com/sonata-project/dev-kit/issues/398

**Comment by jordisala1991** [comment]
Thank you for unifying issues :)

**Comment by jordisala1991** [comment]
Closing because we already have that dev-kit issue. If you think this is still needed, just reopen. I want to unify all discussions at one place
