### ISSUE TITLE
Why does Export/Exporter.php pass empty string as escape param?

### ISSUE THREAD

**Issue by Kalyse** [sonata-project/SonataCoreBundle#544]
This is more of a general question but unless I'm mistaken: 

https://github.com/sonata-project/SonataCoreBundle/blob/3.x/src/Exporter/Exporter.php#L60

![vr2_772](https://user-images.githubusercontent.com/199760/41067079-3030b55a-69dc-11e8-860d-0b16756a4842.png)

There is no reason to pass an empty string here? Should the default not be used?

```
public function __construct(
        $filename,
        $delimiter = ',',
        $enclosure = '"',
        $escape = '\\',
        $showHeaders = true,
        $withBom = false,
        $terminate = "\n"
    )
```

When we set an escape as an empty string, this casues fputscsv to create a warning. Suppression is okay, but I'm trying to understand why an empty string would ever be used?

If I createa  PR with a single one line update to use \\\\ is this likely to be okay?

**Comment by greg0ire** [comment]
Please report this on the right repository (exporter), and have a look at the git history before, to find the author of this change.
