### ISSUE TITLE
Validation of my second constraint is skipped after the validation of the first constraint passed

### ISSUE THREAD

**Issue by jelteliekens** [sonata-project/SonataCoreBundle#551]
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.35.1 3.35.2 The missing Symfony Admin Generator
sonata-project/block-bundle              3.12.1 3.12.1 Symfony SonataBlockBundle
sonata-project/cache                     1.1.1  2.0.1  Cache library
sonata-project/cache-bundle              2.4.2  3.0.0  This bundle provides caching services
sonata-project/classification-bundle     3.6.1  3.7.1  Symfony SonataClassificationBundle
sonata-project/core-bundle               3.9.1  3.10.0 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.1  2.3.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.5.1  3.6.1  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.8.0  1.9.0  Lightweight Exporter library
sonata-project/formatter-bundle          3.4.1  3.5.0  Symfony SonataFormatterBundle
sonata-project/intl-bundle               2.4.0  2.5.0  Symfony SonataIntlBundle
sonata-project/media-bundle              3.10.2 3.14.0 Symfony SonataMediaBundle
sonata-project/notification-bundle       3.3.1  3.5.1  Symfony SonataNotificationBundle
sonata-project/page-bundle               3.8.0  3.9.0  This bundle provides a Site and Page management through container and block services
sonata-project/seo-bundle                2.5.1  2.5.1  Symfony SonataSeoBundle
sonata-project/user-bundle               4.1.1  4.2.2  Symfony SonataUserBundle
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/monolog-bundle     v3.2.0  v3.3.0 Symfony MonologBundle                    
symfony/phpunit-bridge     v3.4.8  v4.1.1 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.7.0  v1.8.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-ctype     v1.8.0  v1.8.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-icu  v1.7.0  v1.8.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.7.0  v1.8.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.7.0  v1.8.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.7.0  v1.8.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72     v1.7.0  v1.8.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-util      v1.7.0  v1.8.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.1  v3.0.1 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.7  v3.2.2 Symfony SwiftmailerBundle
symfony/symfony            v3.4.11 v4.1.1 The Symfony PHP framework
symfony/var-dumper         v4.0.8  v4.1.1 Symfony mechanism for exploring and dumping PHP variables
```

#### PHP version

```
$ php -v
PHP 7.1.17-1+0~20180505045956.17+jessie~1.gbpde69c6 (cli) (built: May  5 2018 05:17:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.17-1+0~20180505045956.17+jessie~1.gbpde69c6, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
    with blackfire v1.20.0~linux-x64-non_zts71, https://blackfire.io, by Blackfire
```

## Subject
I've added a property `heroImage` of type `Media` to the `Page` entity. In the corresponding `PageAdmin` I added this field to the form in the method `configureFormFields(...)` and added two constraints for it in `validate(...)`. After submitting, the form is successfully validated even though it should have failed. The validation of my second constraint (the one that should fail) is skipped after the validation of the first constraint passed.

I've been testing it with multiple constraint too. From the moment the first condition is passed, all the other constraints are skipped even though at least one should fail.

I suppose it has to do something with the validation of a property that references to another class because I've been trying to get this behaviour on a normal text field but everything works as expected. But when I tried on a other property with type `Page` I was able to reproduce it again.

## Steps to reproduce
In the example below I use `new Assert\IsTrue()` as constraint where I my project I use a custom constraint but the behaviour is exactly the same. This is easier just easier to explain.

### Page.php
```php
    /** @var Media */
    protected $heroImage;
```

### PageAdmin.php
```php
    public function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->with('form_page.group_main_label')
            ->add(
                'heroImage',
                'sonata_type_model_list',
                array(
                    'required' => true,
                ),
                array(
                    'link_parameters' => array(
                        'context' => 'hero',
                        'provider' => 'sonata.media.provider.image',
                        'hide_context' => true,
                    ),
                )
            )
            ->end()
        ;
    }

    public function validate(AdminInterface $admin, ErrorElement $errorElement, $object)
    {
        $errorElement
            ->with('heroImage')
                ->addConstraint(new Assert\NotNull())
                ->addConstraint(new Assert\IsTrue())
            ->end()
        ;
    }
```

## Expected results
There are 3 cases:
1) I leave the image empty
   * NotNull: failed
   * IsTrue: failed

   ==> Works as aspected: Submitting the form failed because not all requirements are met and both the error messages are shown.

2) I upload an image
   * NotNull: passed
   * IsTrue: **skipped**

   ==> **Doesn't work as aspected**: Submitting the form **succeeded** without errors even though it should (the object is not identical to `true`). No error messages are shown.

3) I switch the order of the constraints in the `validate` method and I upload an image.
   * IsTrue: **failed**
   * NotNull: passed

   ==> Works as aspected: Submitting the form failed again because of the first constraint. The error message fo the first constraint is shown.

## Actual results

In case number 2, the form should fail and show an error message.

**Comment by OskarStark** [comment]
This looks like a Symfony issue, are you sure this is related to sonata?

**Comment by core23** [comment]
Can you please check, if this error exists in symfony too? @jelteliekens

**Comment by core23** [comment]
Sorry, but we try to keep github issues for feature requests and bugs only. 

- Please have a look at the [sonata docs](https://sonata-project.org/bundles/)
- Use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and help others as well
- Join #sonata on [the symfony-devs slack](https://symfony.com/slack-invite) for immediate help
