### ISSUE TITLE
sonata-media bundle needs new core-bundle release

### ISSUE THREAD

**Issue by AlexandraNegrea** [sonata-project/SonataCoreBundle#56]
Hey guys! I'm working on a project and developed a back-office using the variety of sonata bundles. The problem is every time I try to add a new media with the sonata-media bundle I get this error:
![error](https://cloud.githubusercontent.com/assets/6952640/2777375/455d5348-cae4-11e3-959b-c283d44585f6.png)

As you can hopefully see symfony can't find the Metadata class in the vendor. Because it doesn't exist. I saw that you recently added the files. Please make a new release (because I know after adding the files in the vendor myself it works beautifully). Thanks!

**Comment by core23** [comment]
Does the problem still exist? @AlexandraNegrea

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.
