### ISSUE TITLE
Add support for others export formats (like XmlExcel)

### ISSUE THREAD

**Issue by psyray** [sonata-project/SonataCoreBundle#577]
## Feature Request

Add support for others formats offered by the Exporter Bundle.

Currently Sonata is able to export in XLS, XML, JSON and CSV format.
Exporter bundle supports alternatives to this format, like XmlExcel for xls

XLS format is an HTML export and is not really good, because of the warning message at every opening, the number format (eg for phone, a +36-82-505-800/3106 phone number is displayed -551,257566 in Excel) and others things.

For my project it's a kind of problem. So I look into the Exporter bundle and found that there is a lot of others formats, like the XML Excel one.

I have tested by easily adding [service in the Exporter bundle](https://github.com/sonata-project/exporter/blob/1.x/src/Bridge/Symfony/Resources/config/services.xml) and case [in the switch of the Sonata Core Exporter class](https://github.com/sonata-project/SonataCoreBundle/blob/65e002828f83f604970aa87f247340a80ce9dc95/src/Exporter/Exporter.php#L44) and it's working well.

Does this format could directly be integrated into Sonata Core ?
I think this could be an added value for the Sonata export functionality

I could submit the 2 PR, one for Exporter and one for SonataCore

Waiting for your feedback.

**Comment by greg0ire** [comment]
The class where the case is is deprecated, so I don't think you should change it, but a contribution to the exporter bundle could be good, yeah.

**Comment by kunicmarko20** [comment]
IIRC when it comes to a large number of rows, html xls  can handle it while excel fails

**Comment by psyray** [comment]
What is for you large number of rows ? 50, 5 000, 500 000 ?

**Comment by core23** [comment]
Please open a new issue in the https://github.com/sonata-project/exporter project
