### ISSUE TITLE
[BUG] FlashMessageExtension::getFunction#60 is not returning prent::getFunctions();

### ISSUE THREAD

**Issue by esserj** [sonata-project/SonataCoreBundle#601]
### Environment
any
#### Sonata packages
this one

## Subject
FlashMessageExtension::getFunction#60 is not returning prent::getFunctions(); making all twig templates fail when no flash manager is present as \Twig_ExtensionSet required getFunctions result to be array.

## Steps to reproduce
call \Sonata\CoreBundle\Twig\Extension\FlashMessageExtension:getFunctions without a flashManager
## Expected results
the parent getFunctions result to be returned

## Actual results
returns null

**Comment by esserj** [comment]
was broken due to: #590

**Comment by andreypaa** [comment]
This may help you https://github.com/sonata-project/SonataCoreBundle/pull/599
