### ISSUE TITLE
Error message after updating core bundle

### ISSUE THREAD

**Issue by hgabka** [sonata-project/SonataCoreBundle#611]
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
# Put the result here.
```
sonata-project/admin-bundle              3.42.2 3.42.2 The missing Symfony Admin Generator
sonata-project/block-bundle              3.13.0 3.13.0 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.13.1 3.13.1 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.4.0  2.4.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.1.2  1.1.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.6.3  3.6.3  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.10.0 1.10.0 Lightweight Exporter library
sonata-project/media-bundle              3.16.3 3.16.3 Symfony SonataMediaBundle

#### Symfony packages

```
$ composer show --latest 'symfony/*'
# Put the result here.
```
symfony/monolog-bundle     v3.3.1  v3.3.1  Symfony MonologBundle
symfony/phpunit-bridge     v3.4.20 v4.2.1  Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.10.0 v1.10.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-ctype     v1.10.0 v1.10.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-icu  v1.10.0 v1.10.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.10.0 v1.10.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.10.0 v1.10.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.10.0 v1.10.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72     v1.10.0 v1.10.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-util      v1.10.0 v1.10.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.1  v3.0.1  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.7  v3.2.4  Symfony SwiftmailerBundle
symfony/symfony            v3.4.20 v4.2.1  The Symfony PHP framework

#### PHP version

```
$ php -v
# Put the result here.
```
PHP 7.2.12-1+0~20181112102304.11+stretch~1.gbp55f215 (cli) (built: Nov 12 2018 10:23:04) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.12-1+0~20181112102304.11+stretch~1.gbp55f215, Copyright (c) 1999-2018, by Zend Technologies

## Steps to reproduce
Open the sonata dashboard page
## Expected results
The page should appear correctly
## Actual results
Error: 
`Unable to load the "Sonata\Twig\Extension\FlashMessageRuntime" runtime.`

**Comment by kunicmarko20** [comment]
Already fixed in https://github.com/sonata-project/SonataCoreBundle/pull/608. Use `3.x-dev` until we do a release.

**Comment by hgabka** [comment]
Ok, thanks a lot.
