### ISSUE TITLE
BC Break (or just bug) in the following commit

### ISSUE THREAD

**Issue by tristanbes** [sonata-project/SonataCoreBundle#616]
Hi 

The following commit 2days ago breaks the usage of the bundle:
https://github.com/sonata-project/SonataCoreBundle/commit/78c0174bb5dffbc49fcdbd1558ac39f8aa1d9984

See https://github.com/sonata-project/SonataMediaBundle/issues/1502

**Comment by scuben** [comment]
I can confirm this

**Comment by greg0ire** [comment]
I you 100% sure it is that commit and not 43472cc3b30d811080f38ad06564b44e73a8a5e9 ?
