### ISSUE TITLE
Smart REST behavior for boolean parameters in API

### ISSUE THREAD

**Issue by Wharenn** [sonata-project/SonataCoreBundle#67]
When using the API, boolean parameters on POST/PUT requests are not working as naturally expected. 

Currently:
- No data passed for a boolean value will be handled as "false"
- Any data passed (including 0, false, etc.) will be handled as "true"

In REST context, we would expect that if we are providing false or 0 as boolean value it would lead to a final "false".

This behavior is related to the use of forms. A solution can be to use a custom Data Transformer for these cases proper to the API context.

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.
