### ISSUE TITLE
Support sonata-project/datagrid-bundle 3.0

### ISSUE THREAD

**Issue by jaikdean** [sonata-project/SonataCoreBundle#699]
## Feature Request

`sonata-project/datagrid-bundle` 3.0.0 was release a couple of months ago.

**Comment by core23** [comment]
We won't do this. This bundle will be deprecated soon

**Comment by kunicmarko20** [comment]
Wouldn't it be better if the issue was transferred to the new repo?

**Comment by core23** [comment]
I'm not sure if we even need the datagrid bundle for this project...

**Comment by kunicmarko20** [comment]
Maybe admin bundle should have the dependency then?
