### ISSUE TITLE
A lot of deprecations 

### ISSUE THREAD

**Issue by manu-sparheld** [sonata-project/SonataCoreBundle#701]
```php.INFO: User Deprecated: The "sonata.core.model.adapter.chain" service is deprecated in favor of service "sonata.doctrine.model.adapter.chain" since 3.12.0 and will be removed in 4.0. {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"sonata.core.model.adapter.chain\" service is deprecated in favor of service \"sonata.doctrine.model.adapter.chain\" since 3.12.0 and will be removed in 4.0.
php.INFO: User Deprecated: The Sonata\CoreBundle\Model\Adapter\AdapterChain class is deprecated since version 3.12.0 and will be removed in 4.0. Use Sonata\Doctrine\Adapter\AdapterChain instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: The Sonata\\CoreBundle\\Model\\Adapter\\AdapterChain class is deprecated since version 3.12.0 and will be removed in 4.0. Use Sonata\\Doctrine\\Adapter\\AdapterChain instead. 
php.INFO: User Deprecated: The "sonata.core.model.adapter.doctrine_orm" service is deprecated in favor of service "sonata.doctrine.adapter.doctrine_orm" since 3.12.0 and will be removed in 4.0. 
php.INFO: User Deprecated: The Sonata\CoreBundle\Model\Adapter\DoctrineORMAdapter class is deprecated since version 3.12.0 and will be removed in 4.0.```

**Comment by core23** [comment]
Use the latest version and the recommended classes.

**Comment by alfabetagama** [comment]
This is the latest version. Why was this closed?

**Comment by javiereguiluz** [comment]
Could you please reconsider opening this issue? I'm using 3.17.0 version (which is the latest according to https://github.com/sonata-project/SonataCoreBundle/releases) and I'm seeing hundreds of deprecation messages related to Sonata.

I'm using sonata for a CRUD application where I don't do any advanced or internal stuff, so I would say that the deprecations are not caused directly by my code (I can be wrong of course).

Thanks!

**Comment by TristanGie** [comment]
Those deprecations remain with the latest version, which is kinda annoying while trying to build clean CI. I'm not sure why this and #664 are closed since nothing changed in months.

**Comment by core23** [comment]
We are working on this. There is a PR which should solve the issue / make migration possible: https://github.com/sonata-project/SonataCoreBundle/pull/736
