### ISSUE TITLE
Migrate CoreBundle to extensions

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/SonataCoreBundle#741]
## Feature Request

We must consider dropping the CoreBundle in two ways.

## In sonata-project bundles
Some CoreBundle classes extends *-extensions classes. We can not change CoreBundle to *-extensions in sonata-project bundles. We should change `extends` to `class_alias`. This will allow change API and drop CoreBundle in sonata-project bundles.

Issue for that is here https://github.com/sonata-project/dev-kit/issues/697

## In users projects
User must get information about deprecated in IDE. We must deprecated all CoreBundle classes. Some feature like FormHelper must be drop too becouse form type mapping is not support from 3.0 ?? We should also add "Bridge" to Form and Twig. This will allow resolve release problem. We will release CoreBundle, FormBundle and TwigBundle in one package:
```json
 "sonata-project/core-bundle ":  "3.19"
```
and this package will be equal to next release:
```json
 "sonata-project/core-bundle ":  "3.20",
 "sonata-project/form-extensions": "0.1",
 "sonata-project/twig-extensions": "0.1"
```

I prepare v3.19 in 5 RPs:
- [x] [Add deprecations](https://github.com/sonata-project/SonataCoreBundle/pull/742)
- [x] [Add SonataFormBundle (bridge)](https://github.com/sonata-project/SonataCoreBundle/pull/743)
- [x] [Add SonataTwigBunde (bridge)](https://github.com/sonata-project/SonataCoreBundle/pull/744)
- [x] [Add class_aliases](https://github.com/sonata-project/SonataCoreBundle/pull/745)
- [x] [Fix pack with tests ](https://github.com/sonata-project/SonataCoreBundle/pull/746)

CoreBundle v3.20:
- [x] https://github.com/sonata-project/form-extensions/pull/92
- [x] https://github.com/sonata-project/twig-extensions/pull/80
- [x] https://github.com/sonata-project/SonataCoreBundle/pull/752

**Comment by wbloszyk** [comment]
I finish this issue. RTM.

**Comment by jordisala1991** [comment]
This one can be closed right? we can continue on the dev kit issue
