### ISSUE TITLE
Form:color.html.twig and Form:colorpicker.html.twig'

### ISSUE THREAD

**Issue by Webonaute** [sonata-project/SonataCoreBundle#758]
How do I upgrade those template? does not seem to followed up in new packages.

- 'SonataCoreBundle:Form:color.html.twig'
- 'SonataCoreBundle:Form:colorpicker.html.twig'

**Comment by franmomu** [comment]
Those templates are used by [`ColorType`](https://github.com/sonata-project/SonataCoreBundle/blob/37cecb2ae52d333ac481ca98ec51630c9a2a834e/src/CoreBundle/Form/Type/ColorType.php) and [`ColorSelectorType`](https://github.com/sonata-project/SonataCoreBundle/blob/37cecb2ae52d333ac481ca98ec51630c9a2a834e/src/CoreBundle/Form/Type/ColorSelectorType.php), if you are using them, you should have some deprecation warnings telling you that those types have been deprecated in favor of [`Symfony\Component\Form\Extension\Core\Type\ColorType`](https://symfony.com/doc/4.4/reference/forms/types/color.html).

**Comment by jordisala1991** [comment]
I think the issue is solved
