### ISSUE TITLE
DateTime error on send

### ISSUE THREAD

**Issue by AlmogBaku** [sonata-project/SonataCoreBundle#83]
I configured the `Sonata dateTime`:
```php
->add('startTime', 'sonata_type_datetime_picker', array(
                'format' => 'd.m.Y, H:i:s'
            ))
```

The form throwing error:
```
 An error has occurred during update of item "My cool item". 
```

**Comment by pulzarraider** [comment]
This probably ends with `InvalidParameterException: PHP Date format 'd.m.Y, H:i:s' is not a convertible moment.js format; please add it to the 'Sonata\CoreBundle\Date\MomentFormatConverter' class by submitting a pull request if you want it supported.`.

The solution for this is add new format in the `MomentFormatConverter` or wait until the #142 will be merged.

**Comment by pulzarraider** [comment]
The PR #142 was merged, so you can use now more datetime formats.

Please use the [ICU formats](http://userguide.icu-project.org/formatparse/datetime#TOC-Date-Time-Format-Syntax), not the php date formats.
```
'format' => 'dd.MM.yyyy, HH:mm:ss'
```
