### ISSUE TITLE
DateTime issue with momentjs

### ISSUE THREAD

**Issue by rande** [sonata-project/SonataCoreBundle#85]
Hello,

I have reverted @na-ji works has some commit breaks:
- [x] https://github.com/sonata-project/SonataCoreBundle/issues/80
- [x] https://github.com/sonata-project/SonataAdminBundle/issues/2261
- [x] https://github.com/sonata-project/SonataAdminBundle/issues/2255
- [x] https://github.com/sonata-project/SonataAdminBundle/issues/1887
- [x] https://github.com/sonata-project/sandbox/issues/400

Related commits:
- 294d70b79f657d125f7c26b8d1f8402185c442c6
- 6af1033009c7fc0dafbc11fdc98aca8b07db775b
- 1f7b88fb80f135d286d281537fb54a48b29b807a

There is also others reference of this issue in the SonataAdminBundle.

**Comment by AntonioCS** [comment]
Has this been adopted by the bundle? I didn't set anything but the element with sonata_type_datetime_picker has the attribute 'data-date-format' => 'YYYY-MM-DDTHH:mm:ssZZ'.
This looks horrible to the user

**Comment by debach** [comment]
In order to change the format and the language of the `sonata_type_datetime_picker`, I had to set the following options,

    ->add('when', 'sonata_type_datetime_picker', array(
              'dp_language' => 'de',
              'format' => 'dd.MM.yyyy, HH:mm',
              'attr' => array(
                  'data-date-format' => 'DD.MM.YYYY, HH:mm',
              ))

and load the moment.js locale manually by

    {% javascripts
         '@SonataCoreBundle/Resources/public/vendor/moment/locale/de.js'
    %}
        <script src="{{ asset_url }}"></script>
    {% endjavascripts %}

Is this intended? It’s not at all obvious from the documentation.

**Comment by AntonioCS** [comment]
@debach commented on [29 Jan 2015 10:44 GMT](https://github.com/sonata-project/SonataCoreBundle/issues/85#issuecomment-72004662 "2015-01-29T10:44:27Z - Replied by Github Comment Enhancer"):
> In order to change the format and the language of the `sonata_type_datetime_picker`, I had to set the following options,
> 
>  -&gt;add('when', 'sonata_type_datetime_picker', array(
>            'dp_language' =&gt; 'de',
>            'format' =&gt; 'dd.MM.yyyy, HH:mm',
>            'attr' =&gt; array(
>                'data-date-format' =&gt; 'DD.MM.YYYY, HH:mm',
>            ))
>  `</pre>
> 
>  and load the moment.js locale manually by
> 
>  <pre>`{% javascripts
>       '@SonataCoreBundle/Resources/public/vendor/moment/locale/de.js'
>  %}
>      &lt;script src="{{ asset_url }}"&gt;&lt;/script&gt;
>  {% endjavascripts %}
> 
> Is this intended? It’s not at all obvious from the documentation.

I didn't have to add any js.
So people don't have to guess what a valid format is I advise anyone that wants to change the format to check out the file /vendor/sonata-project/core-bundle/Date/MomentFormatConverter.php.

There you will see:

    
```
private $phpMomentMapping = array(
        "yyyy-MM-dd'T'HH:mm:ssZZZZZ" => 'YYYY-MM-DDTHH:mm:ssZZ', // 2014-05-14T13:55:01+02:00
        "yyyy-MM-dd"                 => 'YYYY-MM-DD',            // 2014-05-14
        "dd.MM.yyyy, HH:mm"          => 'DD.MM.YYYY, HH:mm',     // 14.05.2014, 13:55, German format without seconds
        "dd.MM.yyyy, HH:mm:ss"       => 'DD.MM.YYYY, HH:mm:ss',  // 14.05.2014, 13:55:01, German format with seconds
        "dd/MM/yyyy"                 => 'DD/MM/YYYY',            // 14/05/2014, British ascending format
        "dd/MM/yyyy HH:mm"           => 'DD/MM/YYYY HH:mm',      // 14/05/2014 13:55, British ascending format with time
        "EE, dd/MM/yyyy HH:mm"       => 'ddd, DD/MM/YYYY HH:mm', // Wed, 14/05/2014 13:55, includes day of week in British format
    );
```

Good luck!

**Comment by webdevilopers** [comment]
In order to add the `de` language i had to add the js too as @debach suggested.
My example also worked without the `data-date-format` attribute.

I needed the german date format without time. Though I used the `sonata_type_date_picker` (instead of `sonata_type_datetime_picker`) Moment uses the full format `dd.MM.yyyy, HH:mm:ss`.

I added the german date format without time:
```php
class MomentFormatConverter
{
    /**
     * @var array This defines the mapping between PHP ICU date format (key) and moment.js date format (value)
     * For ICU formats see http://userguide.icu-project.org/formatparse/datetime#TOC-Date-Time-Format-Syntax
     * For Moment formats see http://momentjs.com/docs/#/displaying/format/
     */
    private $phpMomentMapping = array(
        "yyyy-MM-dd'T'HH:mm:ssZZZZZ" => 'YYYY-MM-DDTHH:mm:ssZZ', // 2014-05-14T13:55:01+02:00
        "yyyy-MM-dd"                 => 'YYYY-MM-DD',            // 2014-05-14
        "dd.MM.yyyy"                 => 'DD.MM.YYYY',            // 14.05.2014, German format without time
        "dd.MM.yyyy, HH:mm"          => 'DD.MM.YYYY, HH:mm',     // 14.05.2014, 13:55, German format without seconds
        "dd.MM.yyyy, HH:mm:ss"       => 'DD.MM.YYYY, HH:mm:ss',  // 14.05.2014, 13:55:01, German format with seconds
        "dd.MM.yyyy"                 => 'DD.MM.YYYY',            // 14.05.2014, German format without time
        "dd/MM/yyyy"                 => 'DD/MM/YYYY',            // 14/05/2014, British ascending format
        "dd/MM/yyyy HH:mm"           => 'DD/MM/YYYY HH:mm',      // 14/05/2014 13:55, British ascending format with time
        "EE, dd/MM/yyyy HH:mm"       => 'ddd, DD/MM/YYYY HH:mm', // Wed, 14/05/2014 13:55, includes day of week in British format
    );
```

My example now works:
```php
        $formMapper
                ->add('date', 'sonata_type_date_picker', array(
                        'dp_language' => 'de',
                        'format' => 'dd.MM.yyyy'
                ));
```

Should I create a PR in order to add this format?

**Comment by Bladrak** [comment]
You can create a PR indeed, however I'd like to ask why did you add it twice?

**Comment by webdevilopers** [comment]
So there will be no parser that will completely replace the mapping @Bladrak ?

I see there is a open PR by @caponica . Maybe he could add the german format to his changed file:
https://github.com/sonata-project/SonataCoreBundle/pull/93/files

Funny one, looks like a had a local copy where I added the line some weeks ago already.
And just added another line blindly when starting working on the issue again! ;)

**Comment by Bladrak** [comment]
Well the mapper isn't there yet, and we don't have an ETA on it, so in the mean time adding your format to the mapping seems a good option.
Regarding the PR from @caponica I think you can create a new one, so you won't be inter-dependent on this.

**Comment by webdevilopers** [comment]
Just recognized that the german format was already introduced by @krewetka :+1: 
- https://github.com/sonata-project/SonataCoreBundle/commit/645589d8fbdacfaab9a792072e74fc97bcaba4c9

**Comment by krewetka** [comment]
Yeap, I added it a while ago :) 

I also needed format without time... for me it Polish not German but looks the same ;-)

**Comment by webdevilopers** [comment]
Germish polan date format. :)

**Comment by webdevilopers** [comment]
I use my datepicker and the `de` format inside a batch action:
```php
        $actionForm = $this->get('form.factory')->createNamedBuilder('', 'form')
            ->add('testedAt', 'sonata_type_date_picker', array(
                    'dp_language' => 'de',
                    'format' => 'dd.MM.yyyy',
                ))
            ->getForm();
```

This will create the correct format `dd.MM.yyyy`.

Then in my batch action I am validating the date. But validation fails since the `Symfony\Component\Validator\Constraints\Date` expects the format `yyyy-mm-dd`:
```php
use Sonata\AdminBundle\Controller\CRUDController as Controller;

use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\Date;
use Symfony\Component\Validator\Constraints\NotBlank;

class ElectricalEquipmentAdminController extends Controller
{
    public function batchActionTestIsRelevant(array $selectedIds, $allEntitiesSelected)
    {
        if (count($selectedIds) === 0) return false;

        $parameterBag = $this->get('request')->request;

        // check that a target has been chosen
        if (!$parameterBag->has('testedAt')) {
            return 'flash_batch_test_no_tested_at';
        }

        $testedAt = $parameterBag->get('testedAt');

        $dateConstraint = new Date();
        $dateConstraint->message = 'flash_batch_test_no_tested_at';

        $constraint = new Collection(array(
            'testedAt' => array(
                new NotBlank(),
                $dateConstraint
            )
        ));

        $errorList = $this->get('validator')->validateValue(array('testedAt' => $testedAt), $constraint);

        if (!count($errorList) == 0) {
            return $errorList[0]->getMessage();
        }

        return true;
    }
}
```

Do I need to the change the format on the Date Constraint or does the datepicker "fail" to re-format the date for the Constraint?

**Comment by webdevilopers** [comment]
My problem will probably be solved by https://github.com/symfony/symfony/issues/11925 where a Timestamp constraint will accept a format.

As @stof stated:
```The current string validation is quite useless as it does nto allow changing the format of the string.```

As a workaround I guess I will have to convert my `$parameterBag->get('testedAt')` into a valid `DateTime` object and then pass it to the constraint?

**Comment by krewetka** [comment]
I don't know how it works with batch actions but I had quite a lot of problems with date formats as well.

Just to give you some clue for example in date range filter I had to use datepicker in one format and pass it to doctrine as another one. Not to mention I had to create my own types because default ones didn't work.

Have you tried creating DateTime object from testedAt before passing it to validatior?

According to specification Date constraint:

"Validates that a value is a valid date, meaning either a DateTime object or a string (or an object that can be cast into a string) that follows a valid YYYY-MM-DD format.

So maybe DateTime::createFromFormat() would help?

**Comment by krewetka** [comment]
Ok, I see I was a minute to late with my suggestion ;)

**Comment by webdevilopers** [comment]
Two are better than one @krewetka ! BTW: I almost answered my own question on a batchAction in that CRUDController some lines later. The Constraint will work with:
```php
$testedAt = new \DateTime($parameterBag->get('testedAt'));
```

**Comment by rccc** [comment]
Hello,

I am really confused with this sonta_type_date_picker.

Is there a clean and easy documentation to understand how to use it ?

I am using like this : 

`````
            ->add('releaseDate', 'sonata_type_date_picker', array(
                'required' => false,
            ))
`````

The datepicker language is "en", i wish it could be "fr". 

The format is "8 Aug 2012" and then the validation says "format is not valid".

Somme people says they have to import a js lib. Some other  people says they didn't have to import js lib.

I don't understand why it's a **struggle** to use a datepicker in sonata :)

I  wish it could be simple as just specify "fr" and "dd mm yyyy" ( for example) and then it could works properly.

Cheers

**Comment by jcrombez** [comment]
The "language" option is set to your locale, so it should be "fr" in the embeded javascript near your field.

What the bundle is not providing automaticaly, is the translation file related to your language.
You have to add it yourself (at least it's the only way i found) and it's located in : 

/bundles/sonatacore/vendor/moment/locale/fr.js

If you are using SonataAdminBundle, i'm not sure what's the best way to add it.

Don't you guys think this should be added to the documentation ?

**Comment by drAlberT** [comment]
:+1:  the bundle should either provide it automatically or **document** this necessity

**Comment by rande** [comment]
There is a check available in the template https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/standard_layout.html.twig#L66-L70

**Comment by drAlberT** [comment]
@rande yes, I used it in my custom template

**Comment by rande** [comment]
@drAlberT so as the code is inside the main template, there is no problem ? (except for people you are overwritten the original template)

**Comment by drAlberT** [comment]
@rande here is my simple override:

```
{% extends 'SonataAdminBundle::standard_layout.html.twig' %}

{% block logo %}
    {% spaceless %}
    <a class="logo" href="/">
        {% if 'single_image' == admin_pool.getOption('title_mode') or 'both' == admin_pool.getOption('title_mode') %}
            <img src="{{ asset(admin_pool.titlelogo) }}" alt="{{ admin_pool.title }}">
        {% endif %}
        {% if 'single_text' == admin_pool.getOption('title_mode') or 'both' == admin_pool.getOption('title_mode') %}
            <span>{{ admin_pool.title }}</span>
        {% endif %}
    </a>
    {% endspaceless %}
{% endblock %}

{% block side_bar_after_nav %}
<p class="text-center small" style="border-top: 1px solid #444444; padding-top: 10px; position: absolute; bottom: 0; width: 100%;"><a href="http://1-618.it" rel="noreferrer" target="_blank">&copy; 1·618</a></p>
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {% stylesheets
        '@SonataTranslationBundle/Resources/public/css/sonata-translation.css'
    %}

    <link rel="stylesheet" href="{{ asset_url }}" />
    {% endstylesheets %}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {% javascripts
                    "@colorpicker_js"
    %}
    <script type="text/javascript" src="{{ asset_url }}"></script>

    {% set locale=app.request.locale %}
    {% if locale[:2] != 'en' %}
        <script src="{{ asset('/bundles/sonatacore/vendor/moment/locale/' ~ locale|replace({'_':'-'}) ~ '.js') }}"></script>
    {% endif %}
    {% endjavascripts %}

    <script type="text/javascript">
        $(window).load( function() {
            $('.color-picker-control').iris('option', 'change', function(e, ui) {
                    $('.admin-color-preview').css('border-color', ui.color.toString());
            });
        });
    </script>
{% endblock %}
```

It's quite strange I have to rewrite something that should already exists in the main template ... 
so I rechecked *now* removing the code from my override and .. IT works!!

What version of sonata admin introduced that JS? maybe 2.3 lacks it? ... ghosts?  :)

**Comment by rande** [comment]
@drAlberT you are right the 2.3 version is missing this js code: https://github.com/sonata-project/SonataAdminBundle/blob/2.3/Resources/views/standard_layout.html.twig

**Comment by drAlberT** [comment]
Yes just seen  ..  mystery solved :+1: 

But .. what is the sonata admin "stable" release to be used? is dev-master the right choice? IMHO it is not so clear in the doc ;)

**Comment by guillermogfer** [comment]
So, maybe a PR in 2.3 branch to include this lost fragment of code?

**Comment by egordanilenko** [comment]
Ok, in master branch it works fine with european locales (test at en and fr), but bug in 'ru' locale.
For example:
This on load form:
```
31 июля 2015 г., 17:04:47
```

after change:
```
31 июля 2015 'г'., 17:04:47
```
added ' previos and after acronym of "year" = 'г' and this value is not submitted

```php
class AccountStatusAdmin extends AbstractAdmin
{
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('account','sonata_type_model_list')
            ->add('statusTime','sonata_type_date_picker',array('label'=>'form.label_time'))
            ->add('status')
        ;
        parent::configureFormFields($formMapper);
    }
}
```

locale: ru

**Comment by Neodork** [comment]
Had some problems with the `sonata_type_datetime_picker` on the 2.3 branch. 

using it in a block:

``` php
    array('dueDate', 'sonata_type_datetime_picker', array( ));
```

Will result in a format like:

`July 21, 0000 12:00 AM 21, 0000 12:00:00 am`

Went to dev-master and added format and date_format. Now it seems to work.

``` php
    array('dueDate', 'sonata_type_datetime_picker', array(
                   'format' => 'dd.MM.yyyy, HH:mm',
                   'date_format' => 'dd.MM.yyyy, HH:mm'
                   )
           ),
```

Anything I am missing?

**Comment by jordisala1991** [comment]
This issue is old and probably fixed on latest sonata versions, probably thanks to #370 . Lets close this one, if someone stills think this is relevant, just ping me.
